### ISSUE TITLE
Azure IDP implementation broken

### ISSUE THREAD

**Issue by Sidewinder53** [pomerium/pomerium#1050]
## What happened?
When using the Azure IDP implementation, Pomerium does not retrieve all user data or may not process it properly.
This issue blocks access to all configured applications as Pomerium will match the invalid user data with the configured policy. 

Your help is appreciated!

## What did you expect to happen?
The Azure IDP implementation should provide the requested information.

## How'd it happen?

The following data is shown after a successful Azure AD sign in on the Pomerium HTTPS endpoint:
```
Name: <AD Display name>
UserID: qm5pToiuIWNnS8o8WS_SNcbE2Q2<16 char redacted>
User: qm5pToiuIWNnS8o8WS_SNcbE2Q2<16 char redacted>
Group: ec9a2ef9-c01c-4525-8057-<12 char redacted>
Expiry: 2020-07-08 22:08:10 +0000 UTC
Issued: 2020-07-08 21:08:11 +0000 UTC
Issuer: <Pomerium HTTPS endpoint>
Audience: <Pomerium HTTPS endpoint>
```

Note, that the value of UserID and User are equal but none of them show the email address of the user, which is configured in Azure AD. The following API permissions are configured:
![image](https://user-images.githubusercontent.com/19623985/86972525-6221bf00-c173-11ea-8f43-458ed5f69ad7.png)

**Could the problem be related to these permissions?** I have followed the Quickstart Guide, but noticed that the Azure AD set up section seems to show an older version the Azure Portal and doesn't mention 5 Azure Active Directory Graph permissions which are set in the screenshot but not granted by default.

## What's your environment like?

- Pomerium version: Pomerium 0.9.2-1592838263+3b74053
- Ubuntu 20.04, Running with docker-compose using Forward Authentication with traefik

## What's your config.yaml?

```config.yaml
pomerium_debug: true
insecure_server: true
address: :80
forward_auth_url: http://auth
authenticate_service_url: https://auth.redacted.domain.example.com

idp_provider: azure
idp_client_id: <secret>
idp_client_secret: <client>
idp_provider_url: https://login.microsoftonline.com/<endpoint id>/v2.0

cookie_secret: <secret>
shared_secret: <secret>

policy:
- from: https://traefik.redacted.domain.example.com
  to: http://traefik
  allowed_users:
    - <Azure AD user>
- from: https://third-party.example.com
  to: http://<app dns-name>
  allowed_users:
    - <Azure AD user>
```

## What did you see in the logs?
[pomerium.log](https://github.com/pomerium/pomerium/files/4893352/pomerium.log)

**Comment by cuonglm** [comment]
@Sidewinder53 Could you please re-try with the master branch?

There's change in master which has new mechanism to retrieve user's directory information.

**Comment by Sidewinder53** [comment]
@cuonglm Certainly. The docker image from the master branch does in fact change the behavior, unfortunately the information returned is still not enough to match the policy settings:
![image](https://user-images.githubusercontent.com/19623985/87187033-cae07700-c2ec-11ea-9bec-d1c848f634a9.png)

The GUID in the UserID corresponds to the Object ID of the Azure AD user object.

**Comment by cuonglm** [comment]
> @cuonglm Certainly. The docker image from the master branch does in fact change the behavior, unfortunately the information returned is still not enough to match the policy settings:
> ![image](https://user-images.githubusercontent.com/19623985/87187033-cae07700-c2ec-11ea-9bec-d1c848f634a9.png)
> 
> The GUID in the UserID corresponds to the Object ID of the Azure AD user object.

With master branch, you need to setup service account for syncing directory correctly. See https://master.docs.pomerium.io/docs/identity-providers/azure.html#service-account

**Comment by Sidewinder53** [comment]
Sorry, I wasn't sure if this section is required. I configured the service account, but the logs mention an error:
```
5:42AM WRN failed to refresh directory users and groups error="azure: error querying api: 403 Forbidden" service=identity_manager
```

I created this JSON document:
```
{
  "client_id": "<redacted>",
  "client_secret": "<redacted>",
  "directory_id": "<redacted>"
}
```

I converted the JSON document into a string and encoded it with base64.
Any ideas what I'm missing here?

**Comment by cuonglm** [comment]
> Sorry, I wasn't sure if this section is required. I configured the service account, but the logs mention an error:
> 
> ```
> 5:42AM WRN failed to refresh directory users and groups error="azure: error querying api: 403 Forbidden" service=identity_manager
> ```
> 
> I created this JSON document:
> 
> ```
> {
>   "client_id": "<redacted>",
>   "client_secret": "<redacted>",
>   "directory_id": "<redacted>"
> }
> ```
> 
> I converted the JSON document into a string and encoded it with base64.
> Any ideas what I'm missing here?

I think the error dues to mis-configuration in Azure, maybe @desimone @calebdoxsey will have idea how to configure the scope.

**Comment by sylr** [comment]
I don't know if it is relevant to this issue but know that if a user has more than a certain number of groups (200 IIRC) Azure AD stops replying with groups informations for this user.

**Comment by Sidewinder53** [comment]
The user in question is part of a few groups only, so it shouldn't apply in this case.
Could we get your perspective on this @desimone @calebdoxsey ?

**Comment by AKTheKnight** [comment]
I fixed this by giving the Group.Read.All Application permission, as I believe the group pulling is now done during pomerium startup, hence running as an application before a user signs in:
![image](https://user-images.githubusercontent.com/7502848/87541401-1aca8f80-c699-11ea-8019-6739443c1b0f.png)

**Comment by calebdoxsey** [comment]
Here are the permissions I used while testing:

![Screenshot from 2020-07-15 05-57-15](https://user-images.githubusercontent.com/395272/87542374-159d1e80-c660-11ea-81e2-f6d98b50d773.png)

**Comment by AKTheKnight** [comment]
OOh you have quite a few more permissions than I have used. I might do some tests and see what's the minimum before pomerium has issues

**Comment by Sidewinder53** [comment]
@AKTheKnight and @calebdoxsey Thank you very much for your help!
Unfortunately, I still don't get enough information to allow sign-in to my applications.

These are my API settings:
![image](https://user-images.githubusercontent.com/19623985/87574681-04d7c180-c6cf-11ea-9828-c399470c128d.png)

This is what /.pomerium shows after a restart of the container:
![image](https://user-images.githubusercontent.com/19623985/87574836-40728b80-c6cf-11ea-9827-33ee580abe38.png)

Would any of you mind sharing your Pomerium config?

**Comment by AKTheKnight** [comment]
Of course, mine looks like this:
````
authenticate_service_url: https://sso-auth.aktheknight.co.uk
grpc_address: 127.0.0.1:5443

insecure_server: TRUE

IDP_PROVIDER: "azure"
IDP_PROVIDER_URL: "https://login.microsoftonline.com/f0ac156c-04d2-4e80-a9fb-628a60467e33/v2.0"
IDP_CLIENT_ID: "321eee35-05ea-4344-b354-74350061ada9"
IDP_CLIENT_SECRET: "*REDACTED*"
IDP_SERVICE_ACCOUNT: "*REDACTED really long base 64 string*"

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
cookie_secret: *REDACTED*
shared_secret: *REDACTED*

policy:
  - from: http://portainer.docker.aktheknight.co.uk
    to: http://portainer:9000
    allowed_groups:
      - 01f4cb08-bfce-4766-85f2-e600eaba3668
````

**Comment by calebdoxsey** [comment]
@Sidewinder53 there's another step I forgot about. Did you do: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-python-daemon#standard-user

> If you're a standard user of your tenant, then you need to ask a global administrator to grant admin consent for your application. To do this, give the following URL to your administrator:

    https://login.microsoftonline.com/Enter_the_Tenant_Id_Here/adminconsent?client_id=Enter_the_Application_Id_Here

> Where:

> Enter_the_Tenant_Id_Here - replace this value with the Tenant Id or Tenant name (for example, contoso.microsoft.com)
> Enter_the_Application_Id_Here - is the Application (client) ID for the application you registered.

**Comment by Sidewinder53** [comment]
@calebdoxsey Good point! However, I have already granted admin consent trough the Azure Portal.

I have tweaked my API permissions to look exactly like calebdoxsey's and now I do see the group IDs the user is part of:
![image](https://user-images.githubusercontent.com/19623985/87709160-23f45300-c7a4-11ea-9af8-9a4e2489f273.png)

Still no email though.
What version are you all running? Are you on the master branch as recommended by @cuonglm ?

Thanks for your help so far!

**Comment by cuonglm** [comment]
@Sidewinder53 With current [master](59c17fb497d6a3d7a4da0febcffe9ca8328af46d), you will see both group id and group name in your group.

See [this commit](https://github.com/pomerium/pomerium/commit/ee1f9093eeff853e1c6a241c8ac2ae5ac900b35c) for more details.

**Comment by Sidewinder53** [comment]
I have no idea what's wrong.. 😅
![image](https://user-images.githubusercontent.com/19623985/87830109-ae11e980-c880-11ea-8b71-8b9e64644898.png)

**Comment by desimone** [comment]
I've seen this issue with Azure before but was not able to personally reproduce

See https://github.com/pomerium/pomerium/issues/520

**Comment by Sidewinder53** [comment]
I have decided to replace Azure with AWS Cognito, as I don't really see any solution for that. Thanks for your help so far.

**Comment by toonsevrin** [comment]
adding the application Group.Read.All permission solved this issue for me as well, just make sure to restart your pomerium pods!

**Comment by Sidewinder53** [comment]
So I just tried setting this up with 0.10 and noticed that there are a whole bunch of new configuration requirements, such as an authorize-service-url and certificate deployment for internal communication. Is there a guide how to configure all of this? The doc guides don't mention these topics, it's just the config reference having many more (required) options.

**Comment by desimone** [comment]
Hi @Sidewinder53  could you elaborate a bit more. The biggest change was that a [service account needs to be provided](https://www.pomerium.io/docs/upgrading.html#service-accounts-required-for-groups-and-directory-data) to pull back directory sync data in v0.10. We have a patch release incoming that has a PR (https://github.com/pomerium/pomerium/pull/1300) that will  pull some of that data from the existing idp url directly.

**Comment by Sidewinder53** [comment]
My Pomerium config includes all the required idp parameters, such as `idp_provider`, `idp_provider_url`, `idp_client_id`, `idp_client_secret `and `idp_service_account`. That is, according to the guide.

However, when starting the Pomerium container, it crashes after a few seconds:
```
2:44PM INF cmd/pomerium version=v0.1.0+53bfa4e
2:44PM DBG add group group=<group id> route=<route endpoint>
2:44PM DBG add email email=<authorized user> route=<route endpoint>

2:44PM FTL cmd/pomerium: proxy error="missing setting: authorize-service-url"
```

I don't see authorize-service-url being mentioned anywhere (apart from the config reference). As my system is currently running in standalone mode, I tried setting authorize-service-url to localhost (per reference).

```
2:42PM INF cmd/pomerium version=v0.1.0+53bfa4e
2:42PM DBG add group group=<group id> route=<route endpoint>
2:42PM DBG add email email=<authorized user> route=<route endpoint>
2:42PM DBG proxy/clients: using system certificate pool
2:42PM DBG proxy/clients: grpc connection addr=<public auth endpoint> cert-override-name=
2:42PM DBG proxy/clients: using system certificate pool
2:42PM DBG proxy/clients: grpc connection addr=localhost:5443 cert-override-name=
2:42PM DBG cmd/pomerium: http redirect server not started cause="no http redirect addr provided"
2:42PM FTL cmd/pomerium: https server error="https: failed loading x509 certificate: certificate file /pomerium/cert.pem not readable"
```

Is there any reason why I suddenly need to set up certificates for internal communication when I just want to use Pomerium in standalone mode?

**Comment by Sidewinder53** [comment]
@desimone Thanks for pointing this out, this was a stupid oversight.

I have re-configured the configuration, and while I can now log in just fine, I'm still faced with the issues mentioned previously.
I don't see any user details at all. 

Pomerium logs this line:
`7:49AM WRN failed to refresh directory users and groups error="azure: error querying api: 403 Forbidden" service=identity_manager
`

However, idp_service_account is defined and API permissions in the Application configuration are set. Any ideas? Is it possible to log the request made to the API?
Also, you posted some links regarding user scopes, can you elaborate which claims would be required for the application?

**Comment by lukasmrtvy** [comment]
I am using this:

```
serverApplicationId=$(az ad app create \
    --display-name "platform-oauth-app" \
    --identifier-uris https://authenticate.pomerium.example.com/ \
    --reply-urls https://authenticate.pomerium.platform.example.com/oauth2/callback \
    --query appId -o tsv)

az ad sp create --id $serverApplicationId    

az ad app update --id $serverApplicationId --set groupMembershipClaims=SecurityGroup

serverApplicationSecret=$(az ad sp credential reset \
    --name $serverApplicationId \
    --credential-description "passwd" \
    --query password -o tsv)

az keyvault secret set \
  --name pomerium-oauth-secret \
  --vault-name base-deployment-keyvault \
  --value $serverApplicationSecret \
  --tags id=$serverApplicationId

graphId=$(az ad sp list --query "[?appDisplayName=='Microsoft Graph'].appId | [0]" --all -o tsv)

az ad app permission add \
    --id $serverApplicationId \
    --api $graphId \
    --api-permissions $(az ad sp show --id $graphId --query "appRoles[?value=='Group.Read.All'].id | [0]" -o tsv)=Role 

az ad app permission grant \
  --id $serverApplicationId \
  --api $graphId \
  --expires never 

az ad app permission admin-consent --id  $serverApplicationId
```

* `groupMembershipClaims=SecurityGroup` -> only groups from AAD, not synced ones from AD
* `az ad sp show --id $graphId --query "appRoles[?value=='Group.Read.All'].id | [0]" -o tsv` -> Application, instead of Delegation ( appRole vs oauth2Permissions )

As someone pointed here,  seems that Pomerium is downloading groups after startup ( You have to restart deployment after azure app change, I had hard times with it :( . I beliveve that it can be imporved somehow... )

Also if You are look at picture in https://github.com/pomerium/pomerium/issues/1050#issuecomment-659596329, its trying to download  profilePhoto from https://graph.microsoft.com/v1.0/me/photo/$value ( You will get `Failed to load resource: the server responded with a status of 401 (Unauthorized)` in browser ) ( https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0 )

Last thing I noticed is that if You will use `Sign Out` button in pomerium session dashboard ( https://authenticate.pomerium.example.com/.pomerium ), You will get `AADSTS90102: 'post_logout_redirect_uri' value must be a valid absolute URI.` from Azure Portal.


EDIT:
Its not related to Azure, but `request details` link ( Whole message: If you should have access, contact your administrator and provide them with your request details. ) will redirect You to `beyondcorp.example.com/.pomerium`, instead of `authenticate.pomerium.example.com/.pomerium` , related https://github.com/pomerium/pomerium/issues/867#issuecomment-646486331

**Comment by desimone** [comment]
I'm investigating.

**Comment by desimone** [comment]
Sorry for the delayed response. I wanted to walk through a "clean" azure instance to validate things were working. As a result of that walkthrough, I've found -- at least for my azure deployment, which is relatively simple -- things work as expected though a few doc changes are required. Also, it appears that Azure has finally fixed the bug that required us to ask for full directory read access instead of just groups read access for the applciation (as mentioned by @toonsevrin !), so I've updated that as well. (see https://github.com/pomerium/pomerium/pull/1377)


@Sidewinder53 Could you join slack chat so we could try and debug this in realtime? I'm not quite sure what's going on.

@lukasmrtvy 

Thank you for your detailed post. 

> As someone pointed here, seems that Pomerium is downloading groups after startup ( You have to restart deployment after azure app change, I had hard times with it :( . I beliveve that it can be imporved somehow... )

That is correct. This is to ensure that synced directory data (for now, just groups, but soon this will include other directory information that you may want to write authorization policy against, which needs different refresh periods. This method lets us enforce group membership changes much more quickly and in a more scaleable fashion then pulling groups data on a per-user basis / on a user refresh. It also opens up the door for us to, as I hinted, pull in other directory data which may have different caching thresholds). 

The downside of this approach is there will be an initial bootstrapping phase. In production, we suggest using redis as a data-broker backend. 


> Last thing I noticed is that if You will use Sign Out button in pomerium session dashboard ( https://authenticate.pomerium.example.com/.pomerium ), You will get AADSTS90102: 'post_logout_redirect_uri' value must be a valid absolute URI. from Azure Portal.

This is working as expected for me. Do you mind making a new issue to track this if it is not working for you? I think the hope was this was fixed in https://github.com/pomerium/pomerium/pull/926. 


At this point I am going to close this issue in favor of #520 which I think more accurately describes @Sidewinder53 's remaining issue. 

Please re-open if I've got that wrong. 

Thanks!

**Comment by Sidewinder53** [comment]
I just tried it again with v0.10.3 and configured the API permissions as suggested by the new docs, and it finally works!
I'm convinced, that my issue was caused by the incorrect API permissions (delegated/application-level).
