### ISSUE TITLE
regression: JWT_CLAIMS_HEADERS has no effect in 0.9.x?

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#958]
## What happened?

It was possible previously to set `JWT_CLAIMS_HEADERS=email` to send `X-Pomerium-Claim-Email` request header to upstream, but this is broken in 0.9.x.

## What did you expect to happen?

Setting environment variable `JWT_CLAIMS_HEADERS=email` will send `X-Pomerium-Claim-Email` to upstream.

## How'd it happen?

1. Ran `x`
2. Clicked `y`
3. Saw error `z`

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint):
pomerium/v0.9.0 (+github.com/pomerium/pomerium; c29807c; go1.14.4)

- Server Operating System/Architecture/Cloud:
Docker

## What's your config.yaml?

Configured via environment varable:

```docker-compose.yaml
  pomerium:
    image: docker.io/pomerium/pomerium:master
    container_name: pomerium
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    environment:
      # ...
      JWT_CLAIMS_HEADERS: email
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

**Comment by cuonglm** [comment]
It’s duplicated of https://github.com/pomerium/pomerium/issues/936 and already be fixed in latest master

**Comment by yegle** [comment]
Weird, I'm using https://hub.docker.com/layers/pomerium/pomerium/master/images/sha256-19f2cfc7295576f87b889c5b7eddcb75b68ff5469fad1c5f78912984248fff33?context=explore (built an hour agao) but I can still reproduce this issue.

**Comment by cuonglm** [comment]
@yegle ah, then you have to set `pass_identity_headers: true` per-policy basis. See https://github.com/pomerium/pomerium/commit/8d0deb0732e1bd7f10dad134248a9a221206ff57

**Comment by yegle** [comment]
Looks like this is the downside of using :master build. Thank you for the hint!
